/**
 * IRoutingProtocol.h
 *
 *   Version: 2019-03-12
 *    Author: Jaco ter Braak & Frans van Dijk, University of Twente.
 * Copyright: University of Twente, 2015-2019
 *
 ************************************************************
 *                                                          *
 **                 DO NOT EDIT THIS FILE                  **
 ***         YOU DO NOT HAVE TO LOOK IN THIS FILE         ***
 **** IF YOU HAVE QUESTIONS PLEASE DO ASK A TA FOR HELP  ****
 *****                                                  *****
 ************************************************************
 */

#include <cstdint>
#include <map>
#include <list>
#include "LinkLayer.h"
#include "PacketWithLinkCost.h"

#ifndef IROUTINGPROTOCOL_H_
#define IROUTINGPROTOCOL_H_

namespace framework {

    class IRoutingProtocol {
    public:
        IRoutingProtocol() {
        }
        virtual ~IRoutingProtocol() {
        }

        virtual void init(LinkLayer* linkLayer) = 0;

        virtual void tick(std::vector<PacketWithLinkCost> packetsWithLinkCosts) = 0;

        virtual std::map<int32_t, int32_t> getForwardingTable() = 0;
    };
}

#endif /* IROUTINGPROTOCOL_H_ */
