/**
 * LinkLayer.cpp
 *
 *   Version: 2019-03-12
 *    Author: Jaco ter Braak & Frans van Dijk, University of Twente.
 * Copyright: University of Twente, 2015-2019
 *
 ************************************************************
 *                                                          *
 **                 DO NOT EDIT THIS FILE                  **
 ***         YOU DO NOT HAVE TO LOOK IN THIS FILE         ***
 **** IF YOU HAVE QUESTIONS PLEASE DO ASK A TA FOR HELP  ****
 *****                                                  *****
 ************************************************************
 */

#include "LinkLayer.h"
#include "RoutingChallengeClient.h"

namespace framework {
    LinkLayer::LinkLayer(RoutingChallengeClient* client) {
        this->client = client;
    }

    LinkLayer::~LinkLayer() {
    }

    int32_t LinkLayer::getOwnAddress() {
        return client->getAddress();
    }

    void LinkLayer::transmit(Packet packet) {
        return (client->Transmit(packet));
    }
}

