/**
 * LinkLayer.h
 *
 *   Version: 2019-03-12
 *    Author: Jaco ter Braak & Frans van Dijk, University of Twente.
 * Copyright: University of Twente, 2015-2019
 *
 ************************************************************
 *                                                          *
 **                 DO NOT EDIT THIS FILE                  **
 ***         YOU DO NOT HAVE TO LOOK IN THIS FILE         ***
 **** IF YOU HAVE QUESTIONS PLEASE DO ASK A TA FOR HELP  ****
 *****                                                  *****
 ************************************************************
 */

#include "Packet.h"


#ifndef LINKLAYER_H_
#define LINKLAYER_H_

namespace framework {
    class RoutingChallengeClient;
    class LinkLayer {
    public:
        LinkLayer(RoutingChallengeClient* client);
        virtual ~LinkLayer();


        /**
         * Gets the address within the network, associated with this interface
         * @return address
         */
        int32_t getOwnAddress();

        /**
         * Transmits a packet
         * @param packet
         */
        void transmit(Packet packet);
    private:
        RoutingChallengeClient* client;
    };
}
#endif /* LINKLAYER_H_ */
