/**
 * PacketWithLinkCost.h
 *
 *   Version: 2019-03-12
 *    Author: Frans van Dijk, University of Twente.
 * Copyright: University of Twente, 2019
 *
 ************************************************************
 *                                                          *
 **                 DO NOT EDIT THIS FILE                  **
 ***         YOU DO NOT HAVE TO LOOK IN THIS FILE         ***
 **** IF YOU HAVE QUESTIONS PLEASE DO ASK A TA FOR HELP  ****
 *****                                                  *****
 ************************************************************
 */

#include <cstdint>
#include "Packet.h"

#ifndef PACKETWITHLINKCOST_H_
#define PACKETWITHLINKCOST_H_

namespace framework {

    struct PacketWithLinkCost {
        Packet packet; // The received packet
        int32_t linkCost; // The cost of the link over which the packet was received
    };

} /* namespace framework */

#endif /* PACKETWITHLINKCOST_H_ */#pragma once
