/**
 * Packet.cpp
 *
 *   Version: 2017-03-14
 *    Author: Jaco ter Braak & Frans van Dijk, University of Twente.
 * Copyright: University of Twente, 2015-2019
 *
 ************************************************************
 *                                                          *
 **                 DO NOT EDIT THIS FILE                  **
 ***         YOU DO NOT HAVE TO LOOK IN THIS FILE         ***
 **** IF YOU HAVE QUESTIONS PLEASE DO ASK A TA FOR HELP  ****
 *****                                                  *****
 ************************************************************
 */

#include "Packet.h"

namespace framework {

    Packet::Packet(int32_t sourceAddress, int32_t destinationAddress, DataTable *dataTable1) {
        this->sourceAddress = sourceAddress;
        this->destinationAddress = destinationAddress;
        this->dataTable = dataTable1;
        this->b_isRaw = false;
    }

    Packet::Packet(int32_t sourceAddress, int32_t destinationAddress, std::vector<unsigned char> rawData) {
        this->sourceAddress = sourceAddress;
        this->destinationAddress = destinationAddress;
        this->dataTable = nullptr;
        this->rawData = rawData;
        this->b_isRaw = true;
    }

    Packet::~Packet() {
    }

    int32_t Packet::getSourceAddress() {
        return this->sourceAddress;
    }

    int32_t Packet::getDestinationAddress() {
        return this->destinationAddress;
    }

    DataTable *Packet::getDataTable() {
        return this->dataTable;
    }

    std::vector<unsigned char> Packet::getRawData() {
        return this->rawData;
    }

    bool Packet::isRaw() {
        return this->b_isRaw;
    }

} /* namespace framework */
