/**
 * SimulationState.h
 *
 *   Version: 2015-03-10
 *    Author: Jaco ter Braak, University of Twente.
 * Copyright: University of Twente, 2015-2019
 *
 ************************************************************
 *                                                          *
 **                 DO NOT EDIT THIS FILE                  **
 ***         YOU DO NOT HAVE TO LOOK IN THIS FILE         ***
 **** IF YOU HAVE QUESTIONS PLEASE DO ASK A TA FOR HELP  ****
 *****                                                  *****
 ************************************************************
 */

#ifndef SIMULATIONSTATE_H_
#define SIMULATIONSTATE_H_

namespace framework {
    enum SimulationState {
        Idle, Started, TestRunning, TestComplete, Finished
    };
}



#endif /* SIMULATIONSTATE_H_ */
